In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn. preprocessing import StandardScaler


Importing data

In [55]:
diabetes_p=pd.read_csv("/content/diabetes (1).csv")
diabetes_p.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [56]:
diabetes_p.shape

(768, 9)

In [57]:
diabetes_p.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [58]:
diabetes_p.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [59]:
diabetes_p.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [60]:
diabetes_p.corr()

Pregnancies   Glucose  ...       Age   Outcome
Pregnancies                  1.000000  0.129459  ...  0.544341  0.221898
Glucose                      0.129459  1.000000  ...  0.263514  0.466581
BloodPressure                0.141282  0.152590  ...  0.239528  0.065068
SkinThickness               -0.081672  0.057328  ... -0.113970  0.074752
Insulin                     -0.073535  0.331357  ... -0.042163  0.130548
BMI                          0.017683  0.221071  ...  0.036242  0.292695
DiabetesPedigreeFunction    -0.033523  0.137337  ...  0.033561  0.173844
Age                          0.544341  0.263514  ...  1.000000  0.238356
Outcome                      0.221898  0.466581  ...  0.238356  1.000000

[9 rows x 9 columns]

spliting data into train data and test data

In [61]:
X = diabetes_p.drop(columns="Outcome")
Y = diabetes_p[['Outcome']]

In [62]:
X.head()

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33

[5 rows x 8 columns]

In [63]:
Y.head()

Outcome
0        1
1        0
2        1
3        0
4        1

In [64]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.10)
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((691, 8), (77, 8), (691, 1), (77, 1))

In [65]:
import warnings
warnings.filterwarnings('ignore')


Model building

In [66]:
from sklearn.linear_model import LogisticRegression
log_model =LogisticRegression()
log_model.fit(X_train,Y_train)

from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train,Y_train)


DecisionTreeClassifier()

In [67]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,roc_auc_score,roc_curve

In [68]:
y_pred_train = log_model.predict(X_train)
y_pred_train

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,

In [69]:
y_pred_test = log_model.predict(X_test)
y_pred_test

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0])

In [70]:
accuracy_score(Y_train,y_pred_train)

0.7800289435600579

In [74]:
print(confusion_matrix(Y_train,y_pred_train))

[[394  54]
 [ 98 145]]


In [75]:
print(classification_report(Y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84       448
           1       0.73      0.60      0.66       243

    accuracy                           0.78       691
   macro avg       0.76      0.74      0.75       691
weighted avg       0.78      0.78      0.77       691



In [76]:
accuracy_score(Y_test,y_pred_test)

0.8051948051948052

In [77]:
print(confusion_matrix(Y_test,y_pred_test))

[[51  1]
 [14 11]]


In [78]:
y_pred_test1 = dt_model.predict(X_test)
y_pred_test1

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1])

In [79]:
accuracy_score(Y_test,y_pred_test1)

0.7272727272727273

In [80]:
print(confusion_matrix(Y_test,y_pred_test1))

[[39 13]
 [ 8 17]]


In [82]:
print(classification_report(Y_test,y_pred_test1))

              precision    recall  f1-score   support

           0       0.83      0.75      0.79        52
           1       0.57      0.68      0.62        25

    accuracy                           0.73        77
   macro avg       0.70      0.72      0.70        77
weighted avg       0.74      0.73      0.73        77



SVM

In [83]:
from sklearn.svm import SVC
svc_classifier = SVC(kernel='linear')
svc_classifier.fit(X_train,Y_train)
y_pred_test2 = svc_classifier.predict(X_test)

In [84]:
y_pred_test2

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1])

In [85]:
accuracy_score(Y_test,y_pred_test2)

0.7792207792207793

In [86]:
y_pred_train2 = svc_classifier.predict(X_train)
accuracy_score(Y_train,y_pred_train2)

0.7785817655571635

In [87]:
print(confusion_matrix(Y_test,y_pred_test2))

[[49  3]
 [14 11]]


In [88]:
input_data =(0,	137,	40,	35,	168,	43.1,	2.288,	33 )
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshape= input_data_as_numpy_array.reshape(1,-1)
prediction = svc_classifier.predict(input_data_reshape)
prediction


array([1])

In [89]:
if (prediction[0] == 0 ):
  print("person not diabetes")
else :
    print("person is diabetes")
  
  

person is diabetes


In [90]:
 import pickle 

In [91]:
filename = "train_model.sav"
pickle.dump(svc_classifier,open(filename,"wb"))

In [92]:
loaded_model = pickle.load(open('train_model.sav','rb'))

In [93]:
input_data =(0,	137,	40,	35,	168,	43.1,	2.288,	33 )

input_data_as_numpy_array = np.asarray(input_data)

input_data_reshape= input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data_reshape)

if (prediction[0] == 0 ):
  print("person not diabetes")
else :
    print("person is diabetes")
  

person is diabetes


SVM model giving best accurcy